[project]
name = "dita-valiation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi==0.104.1",
    "openpyxl==3.1.2",
    "pandas==2.1.3",
    "python-multipart==0.0.6",
    "uvicorn[standard]==0.24.0",
]
